name: Realse

env:
  CI_LOGIN: "firas8"
  CI_EMAIL: "firas.gabsi@gmail.com"

on:
  push:
    branches: [ "dev" ]

jobs:
  Build:
    name: 📦 Build project
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.CI_EMAIL }}
      - name: Use Node.js
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install
      - name: Build project
        run: npm run build --if-present
      - name: Run lint
        run: npm run lint

  Test:
    name: 🐛 Unit Tests
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
      #  with:
      #    node-version: '14.x'
      #- name: Run Jest
      #  uses: stefanoeb/jest-action@1.0.3
      #- name: Run tests
      #  run: npm run test

  SecurityScan:
    name: 🧹 Njsscan Check
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: nodejsscan scan
        id: njsscan
        uses: ajinabraham/njsscan-action@master
        with:
          args: '.'

  SonarQube:
    name: 🧹 SonarQube
    runs-on: ubuntu-latest
    needs: [ Build ]
    steps:
      - name: Use Node.js
        uses: actions/checkout@v3

  Release:
    name: 🧰 Release
    runs-on: ubuntu-latest
    needs: [ Test, SecurityScan, SonarQube ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      #- run: git remote set-url origin https://firas8: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@github.com/firas8/test.git
      - run: git config --global user.email $CI_EMAIL
      - run: git config --global user.name $CI_LOGIN
      - run: git checkout main
      - run: git pull
      - run: echo "RELEASE_VERSION=$(npm version major --git-tag-version false)" >> $GITHUB_ENV
      - run: git add .
      - run: git commit -m "Release "$RELEASE_VERSION
      - run: git push
      - run: git checkout dev
      - run: git merge -Xtheirs main --allow-unrelated-histories
      - run: git push
      - run: git checkout main
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.RELEASE_VERSION }}

  Deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    needs: [ Release ]
    steps:
      - name: Use Node.js
        uses: actions/checkout@v3